### PR TITLE
Update action description

### PR DESCRIPTION
**Pull request by ethomson**
Update the description of the action.  Also, update documentation to suggest semantic versioning (`v1`) for the action.

### CODE REVIEW

**Comment by 1138-4EB** [comment]
@ethomson, currently `v1` does not exist. Please, see #16.

**Comment by ethomson** [comment]
Thanks for the heads up @1138-4EB, that's an oversight on our part.

**Comment by 1138-4EB** [comment]
@mscoutermarsh, this PR was a *draft* (not ready to be merged), because `v1` does not exist yet (as commented in https://github.com/actions/create-release/pull/18#issuecomment-551894372 and acknowledged in https://github.com/actions/create-release/pull/18#issuecomment-551894372). Therefore, I think that `v1` should be published ASAP, or this PR should be reverted.

**Comment by ethomson** [comment]
Like I said, @1138-4EB, we'll tag `v1`.

**Pull request merged**
