### PR TITLE
Target commitish

### PR DESCRIPTION
**Pull request by Sander0542**

### CODE REVIEW

**Comment by thanosexcite** [comment]
Thanks a lot @Sander0542. I also need this input added. Would it be possible to please check the failing tests, so that this PR can be reviewed and merged?

**Comment by davelosert** [comment]
@Sander0542 : I would really need the changes of this PR. Are you still working on it? 
If not, do you mind if I'd take over and fix those tests for you?

**Comment by Sander0542** [comment]
Hi @davelosert,

You can take this PR over. I don't have time to fix it. Thanks!

**Comment by davelosert** [comment]
I just saw that PR #32 also fixes this issue - and additionally adds the current context.sha as the default comittish. I think that is a bit of a better approach as in here where it still defaults to master, so I think #32  should be preffered to merge over this here. Sorry @Sander0542 .

**Comment by Sander0542** [comment]
I agree with that @davelosert. PR #32 looks good.

**Pull request closed without merging**
